language: go
go_import_path: github.com/ethereum/go-ethereum
sudo: false
matrix:
  include:
    - os: linux
      dist: trusty
      go: 1.4.2
    - os: linux
      dist: trusty
      go: 1.5.4
    - os: linux
      dist: trusty
      go: 1.6.2
    - os: osx
      go: 1.6.2

    # This builder does the PPA upload (and nothing else).
    - os: linux
      dist: trusty
      go: 1.6.2
      env: PPA
      addons:
        apt:
          packages:
            - devscripts
            - debhelper
            - dput
      script:
        - go run build/ci.go travis-debsrc

install:
  - go get golang.org/x/tools/cmd/cover
script:
  - go run build/ci.go install
  - go run build/ci.go test -coverage -vet
after_success:
  # - go run build/ci.go archive -type tar
env:
  global:
  - secure: U2U1AmkU4NJBgKR/uUAebQY87cNL0+1JHjnLOmmXwxYYyj5ralWb1aSuSH3qSXiT93qLBmtaUkuv9fberHVqrbAeVlztVdUsKAq7JMQH+M99iFkC9UiRMqHmtjWJ0ok4COD1sRYixxi21wb/JrMe3M1iL4QJVS61iltjHhVdM64=
notifications:
  slack:
    secure: DJjopLLeUnvQF6LnCjRF7drgTYp1N5LYj5a5/z8fk5783vnZzJufk/Zel0AEg/Igx9fNKV6PlEWXf9P6Do8cZDFHAvM4vgCTiBaLTo4WEhAl9D/SkyhxPdyBKjKEAO2cPUqCX4+qi23qoXNQnovWbROn6DQ1tZqWFs6xKoT5RQfxigoiQYGL+mUcCOfvTV9vLjeYn2YtFK2g/5lMOYap0Aj15Yo4pgAch6K+MAMzxspWAxj29QO6aZVhAaHMEY/wwARos69lzcD8IWDnHEbRc16bIMRoOdCFehXE8hfWqFDofNOZQXdl0M675UJnKtQvkB5TJgXnAu6QAeGWCkRJMUuHKexXjyd/fgx/Tz+y5zhySp3m9V8kbBOsnNMkOeWd3aFhbJxoWYHoPnH9dj3xbw6ZLH+D+gavXrnlkXSGPbdZ+2M1lTfXxoLV/jBJNb4xwmuFwDlLK34fabXmvcvaC5YFEktlj4Yobtc8/KSRyhjL5FXMi3Qe5px28mNnHejopgrHQoa+TbxbpUYdACFC/QPY5QcHMuIZKPF+arXR1/PU1pBVc17JjuoBd3hwTGMRQadFqsQSbVLx1ptHCYyZKdlmUXaOqg5eTcGR35h0fP8WF4Cqw94oN/tTiKUhkjAcs7qPXds5cbmpBtc7AgNrU6GuUE5cDr8u/+fsvpvLC74=
